version: '3.4'
services:
  web:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./dist:/usr/public/html/gui
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
      - NGINX_ROOT=/usr/public/html/gui
